#!/bin/bash
for i in {10..20..1}
do
  python "/home/pmvanderburg/noetic-husky/bop_ros_ws/src/Husky_scripts/data_visualization/bag_to_images.py" --bag_file "/home/pmvanderburg/noetic-husky/kalibr_workspace/bagfiles/20220909/20220909_sequence_imu_$(printf "%06d" $i)_calib.bag" --output_dir "/home/pmvanderburg/noetic-husky/kalibr_workspace/bagfiles/20220909/20220909_sequence_imu_$(printf "%06d" $i)/left/" --image_topic "/zed_node/left_raw/image_raw_color_throttle"
done
