#!/bin/bash

for i in {2..71}; do # 18,19,20,21,22,23,24,103,104,105,106,107,108,109,94}; do # while read i; do
  #mkdir -p /media/pmvanderburg/T7/bop_datasets/husky/$(printf "%s" $split_type)/$(printf "%06i" $i)
  echo "/media/pmvanderburg/T7/bop_datasets/husky/train/800100/depth" "/media/pmvanderburg/T7/bop_datasets/husky/$(printf "%s" $split_type)/$(printf "%06i" $i)/"
  rsync -aP "/media/pmvanderburg/T7/bop_datasets/husky/train/800100/depth" "/media/pmvanderburg/T7/bop_datasets/husky/$(printf "%s" $split_type)/$(printf "%06i" $i)/"
  #cp -rv "/media/pmvanderburg/T7/bop_datasets/husky/train/800100/depth" "/media/pmvanderburg/T7/bop_datasets/husky/$(printf "%s" $split_type)/$(printf "%06i" $i)/"
done #  < /media/pmvanderburg/T7/bop_datasets/husky/seqlist.txt

rm -rv /media/pmvanderburg/T7/bop_datasets/husky/$(printf "%s" $split_type)/000000
