#!/bin/bash
arg1 = $1
arg2 = $2
print(arg1)
for i in {1..1..1}
do
  cp -v "/home/pmvanderburg/noetic-husky/datasets/bop_datasets/husky/train/$(printf "%06i" $i)/delay_300/scene_gt.json" "/home/pmvanderburg/noetic-husky/datasets/bop_datasets/husky/train/$(printf "%06i" $i)/"
done

